import Head from "next/head";
import { Container, Stack, Text, Title } from "@mantine/core";
import useMyContext from "@/context/my-context";
import EventCard from "@/components/molecules/EventCard";

export default function Index() {
    const { allEvents } = useMyContext();
    return (
        <>
            <Head>
                <title>Explore events ︱ Eventa</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container>
                    <Title order={1} mb="sm">
                        Explore events
                    </Title>
                    <Stack>
                        {allEvents
                            .filter((event) => event.eventIsPublic === "Public")
                            .map((event) => {
                                return <EventCard event={event} key={event.eventId} />;
                            })}
                    </Stack>
                </Container>
            </main>
        </>
    );
}
